<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mukul" failures="1" tests="2" name="class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners" time="10.615" errors="0" timestamp="2025-05-02T10:52:24 IST" skipped="1">
  <testcase classname="class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners" name="testcase2" time="0.000">
    <skipped/>
    <system-out>
      <![CDATA[Test case is skipped
Test case execution done]]>
    </system-out>
  </testcase> <!-- testcase2 -->
  <testcase classname="class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners" name="testcase1" time="10.615">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners.testcase1(TestCaseforListeners.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
    <system-out>
      <![CDATA[Test case started
Test case is falied]]>
    </system-out>
  </testcase> <!-- testcase1 -->
  <system-out>
    <![CDATA[Test case started
Test case is falied
Test case started
Test case is skipped
Test case execution done]]>
  </system-out>
</testsuite> <!-- class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners -->
